var character;
var age;
var isLoggedIn;
var ninjas = [];
ninjas.push('thurain');
var mixed = [];
mixed.push('thurain');
mixed.push(20);
mixed.push(true);
console.log(mixed);
var thurainDev;
thurainDev = { name: 'thurain', age: 20 };
var thurainTwo;
thurainTwo = { name: 'duat', age: 23, isBelt: true };
