var age = 25;
age = true;
console.log(age);
age = 'thurain';
console.log(age);
age = 20;
console.log(age);
var mixed = [];
mixed.push('thurain');
mixed.push(20);
mixed.push(true);
console.log(mixed);
var thurain;
thurain = { name: 'thurain', age: 20 };
console.log(thurain);
